# Generated by Django 5.2.2 on 2025-06-07 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecgdata',
            options={'ordering': ['timestamp'], 'verbose_name': 'ECG Data', 'verbose_name_plural': 'ECG Data'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddIndex(
            model_name='ecgdata',
            index=models.Index(fields=['user', 'timestamp'], name='ecg_data_user_id_e4cac9_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='user_profil_user_id_4f95f8_idx'),
        ),
        migrations.AlterModelTable(
            name='ecgdata',
            table='ecg_data',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
