# Generated by Django 5.2.2 on 2025-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0002_alter_ecgdata_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecgdata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'ECG Recording', 'verbose_name_plural': 'ECG Recordings'},
        ),
        migrations.AlterField(
            model_name='ecgdata',
            name='data',
            field=models.JSONField(verbose_name='ECG Data'),
        ),
        migrations.AlterField(
            model_name='ecgdata',
            name='sample_rate',
            field=models.IntegerField(default=200, verbose_name='Sample Rate (Hz)'),
        ),
        migrations.AlterField(
            model_name='ecgdata',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Recording Time'),
        ),
    ]
