# Generated by Django 5.2.2 on 2025-06-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_app', '0005_profile_blood_type_profile_height_profile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
